# Generated by Django 3.0 on 2020-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('C++', 'C SHARP'), ('PY', 'PYTHON'), ('JS', 'JAVASCRIPT'), ('J', 'JAVA')], max_length=5)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
