# Generated by Django 3.0 on 2020-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('C++', 'C SHARP'), ('PY', 'PYTHON'), ('JS', 'JAVASCRIPT'), ('J', 'JAVA')], default='PYTHON', max_length=5),
        ),
    ]
