# Generated by Django 3.0 on 2020-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20200329_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
